### ISSUE TITLE
cross-walk of the FAIR principles should include the text of the principles

### ISSUE THREAD

**Issue by mr-c** [FAIR-BioRS/Guidelines#2]
Example from a cross-walk of CWL with FAIR https://docs.google.com/document/d/1c5teYDLfSMAPZCUdhkW2Pp7GYcQeFpynM_9zSzFw_BI/edit

**Comment by bvhpatel** [comment]
This has been added here: https://github.com/FAIR-BioRS/Guidelines/blob/main/main/compliance-with-FAIR4RS-principles.md
