### ISSUE TITLE
Consider formulating, packaging, and publishing this in the form of Ten Simple Rules paper

### ISSUE THREAD

**Issue by hlapp** [FAIR-BioRS/Guidelines#4]
The Ten Simple Rules series of PLOS Comp Biol has been very successful and also highly useful in educating researchers and advocating for better practices in various fields, including research software. For example see [Taschuk & Wilson](http://dx.doi.org/10.1371/journal.pcbi.1005412), [List et al](http://dx.doi.org/10.1371/journal.pcbi.1005265), and [Prlic and Procter](http://dx.doi.org/10.1371/journal.pcbi.1002802). There are in fact already also articles in this series on making research components more FAIR, for example [Cox et al](https://doi.org/10.1371/journal.pcbi.1009041) and [Garcia et al](https://doi.org/10.1371/journal.pcbi.1007854).

For wider visibility and impact, and to be in a form that's already been proven to be helpful in promoting better practices, I'd suggest to strongly consider a Ten Simple Rules paper, for example _Ten Simple Rules for Making Research Software More FAIR_. (If you'd then be looking for co-authors, I'd be willing to help.)

**Comment by bvhpatel** [comment]
The FAIR-BioRS guidelines are meant to comply with each of the FAIR4RS principles and therefore likely not suitable into a "Ten simple rule format" (we need as many rules as necessary to comply with each of the FAIR4RS principles.). We hope that the format available here present the FAIR-BioRS guidelines in the most useful way to the community: https://doi.org/10.1101/2022.04.18.488694
